version: 2


build:
  os: "ubuntu-22.04"
  tools:
    # https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python
    python: "mambaforge-22.9"
  commands:
    - "conda install quarto~=1.3.450"
    - "cd doc && quarto render"
    - "mv doc/_site/* $READTHEDOCS_OUTPUT/html/."
