version: 2


build:
  os: "ubuntu-22.04"
  # TODO: There must be a more readable way to express this...
  commands:
    # https://quarto.org/docs/download/tarball.html
    - "wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.450/quarto-1.3.450-linux-amd64.tar.gz"
    - "mkdir ~/opt && tar -C ~/opt -xvzf quarto*.tar.gz"
    - "mkdir ~/bin && ln -s ~/opt/quarto-1.3.450/bin/quarto ~/bin/quarto"
    - "cd doc && ~/bin/quarto render"
    - "mkdir --parents $READTHEDOCS_OUTPUT/html/"
    - "mv doc/_site/* $READTHEDOCS_OUTPUT/html/."
