version: '3.7'

services:

  usaon-benefit-tool:
    image: "nsidc/usaon-benefit-tool:dev"
    # Flask development server with live debugger and hot reloading:
    command: "flask run --host 0.0.0.0"
    build: "."
    # To make volume mounting (especially for new volume mounts like the DB)
    # easier, override the micromamba non-root user:
    user: "root"
    volumes:
      - "./usaon_benefit_tool:/usaon-benefit-tool/usaon_benefit_tool:ro"
      - "./tasks:/usaon-benefit-tool/tasks:ro"
      - "./_db:/db:rw"
    ports:
      - "5000:5000"
    environment:
      # Disable login:
      - "USAON_BENEFIT_TOOL_LOGIN_DISABLED=true"
      # Use a local file DB instead of a remote one:
      - "USAON_BENEFIT_TOOL_DB_SQLITE=true"
        # Enable the in-browser debugger: 
      - "FLASK_DEBUG=True"
      # NOTE: This is temporary until issue #144 is resolved
      # Creds for talking to Google:
      - "USAON_BENEFIT_TOOL_GOOGLE_CLIENT_ID=${USAON_BENEFIT_TOOL_GOOGLE_CLIENT_ID:?USAON_BENEFIT_TOOL_GOOGLE_CLIENT_ID must be set}"
      - "USAON_BENEFIT_TOOL_GOOGLE_CLIENT_SECRET=${USAON_BENEFIT_TOOL_GOOGLE_CLIENT_SECRET:?USAON_BENEFIT_TOOL_GOOGLE_CLIENT_SECRET must be set}"
    

      # Development DANGER ZONE: Do not use the below settings except for
      # development. These settings are insecure in production.

      # In dev, we don't need to secure our sessions
      - "FLASK_SECRET_KEY=supersecret"
      # Allow http in dev
      #     https://flask-dance.readthedocs.io/en/v0.8.0/quickstarts/google.html#code
      - "OAUTHLIB_INSECURE_TRANSPORT=1"
