version: '3.7'

services:

  usaon-vta-survey:
    image: "nsidc/usaon-vta-survey:dev"
    # Flask development server with live debugger and hot reloading:
    command: "flask run --cert=adhoc -h 0.0.0.0"
    build: "."
    ports:
      - "5000:5000"
    environment:
      - "FLASK_DEBUG=True"
      - "FLASK_SECRET_KEY=supersecret"
        # https://flask-dance.readthedocs.io/en/v0.8.0/quickstarts/google.html#code
        # Allow http in dev. DO NOT USE IN PROD.
      - "OAUTHLIB_INSECURE_TRANSPORT=1"
    volumes:
      - "./usaon_vta_survey:/usaon-vta-survey/usaon_vta_survey:ro"
      - "./tasks:/usaon-vta-survey/tasks:ro"
