version: '3.7'

services:

  usaon-vta-survey:
    ports:
      - "5000:5000"
    environment:
      - "FLASK_DEBUG=True"
      - "FLASK_SECRET_KEY=supersecret"
    volumes:
      - "./usaon_vta_survey:/usaon-vta-survey/usaon_vta_survey:ro"
      - "./tasks:/usaon-vta-survey/tasks:ro"
