name: usaon-vta-survey
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python ~=3.10.6

  # Dev dependencies:
  - bump2version ~=1.0
  - invoke ~=1.7
  - pytest ~=7.1
  - mypy ~=0.942
  - shellcheck ~=0.8.0
  - typing-extensions ~=4.4
  - pre-commit

  # Runtime dependencies:
  - flask ~=2.2
  - flask-wtf ~=1.0

  - sqlalchemy ~=1.4
  - psycopg2 ~=2.9
  - flask-sqlalchemy ~=3.0

  - loguru ~=0.6.0

  - pip:
    - wtforms-sqlalchemy ~=0.3
      
  platforms:
    - linux-64
    - osx-64
