name: usaon-benefit-tool
channels:
  - conda-forge
  - nodefaults
platforms:
  - linux-64
  - osx-64
dependencies:
  - python ~=3.11.7

  # Dev dependencies:
  - pre-commit
  - bump-my-version ~=0.9.2
  # TODO: For some reason, with later versions, imports within invoke tasks stop working
  - invoke ~=2.0.0
  - pytest ~=7.1
  - mypy ~=1.7.1
  - shellcheck ~=0.8.0
  - typing-extensions ~=4.4

  # Runtime dependencies:
  - flask ~=2.2
  - flask-wtf ~=1.0
  - flask-dance ~=7.0.0
  - flask-login ~=0.6.2
  - gunicorn ~=21.2
  
  - requests 
  - oauthlib
  - openssl

  - sqlalchemy ~=1.4
  - psycopg2 ~=2.9
  - flask-sqlalchemy ~=3.0

  - loguru ~=0.6.0
  - werkzeug ~=2.2.3

  # Optional dependency enables adhoc ssl certs in dev:
  - pyopenssl

  - pip:
    # TODO: Get these on conda-forge
    - wtforms-sqlalchemy
    - bootstrap-flask ~=2.3.0
