project:
  type: "website"


website:
  title: "US AON Benefit Tool"
  site-url: "https://nsidc.github.io/usaon-benefit-tool"

  repo-url: &repo-url "https://github.com/nsidc/usaon-benefit-tool"
  repo-actions:
    - "edit"
    - "source"
    - "issue"


  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy;"

  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: "github"
        href: *repo-url
    contents:
      - text: "How to"
        href: "how-to/index.md"
        contents: "how-to/*.md"
      - text: "Reference"
        href: "reference/index.md"
        contents: "reference/*.md"

      # Separator:
      - text: "---"

      - text: "Notes"
        href: "notes/index.md"


format:
  html:
    from: "markdown+emoji"
    theme: ["cosmo", "style.scss"]
    toc: true
